# Project
version=2.0.1
group=acaciatide.whohasmending
java_version=21

# Common
minecraft_version=1.21.1
mod_name=Who has Mending?
mod_author=AcaciaTide
mod_id=whohasmending
license=MIT
credits=
mod_description=Displays villager trade information (only enchanted books and their costs) above their heads. Useful for finding mending books!
minecraft_version_range=[1.21,1.22)
neo_form_version=1.21.1-20240808.144430

# Fabric
fabric_version=0.116.12+1.21.1
fabric_loader_version=0.16.10

# NeoForge
neoforge_version=21.1.65
neoforge_loader_version_range=[4,)
neoforge_version_range=[21.1,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false